version: '3.8'

services:
  backend:
    build: ./mern-demo/server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://Tinh:Tinh098970@cluster0.ycp3da4.mongodb.net/mern_db?retryWrites=true&w=majority

  frontend:
    build: ./mern-demo/client
    ports:
      - "5173:5173"
    depends_on:
      - backend